name = "FDMT"
uuid = "7c26793b-8990-4dde-b963-55489d0b7d45"
authors = ["Kiran Shila <me@kiranshila.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
